---
- name: Set map fact
  ansible.builtin.set_fact:
    argocd_map:
      credentials:
        server:
          admin:
            password: "{{ global_map.credentials.argocd.server.admin.password | string | password_hash('blowfish') }}"
          user:
            name: "{{ global_map.credentials.argocd.server.user.name }}"
            password: "{{ global_map.credentials.argocd.server.user.password | string | password_hash('blowfish') }}"
      gateway:
        server:
          annotations:
            cert-manager.io/cluster-issuer: "{{ externaldns_project.cloudflare.cluster.issuer }}"
          hostname: "{{ argocd_vars.kubernetes.server.gateway.subdomain }}.{{ externaldns_vars.cloudflare.host.domain }}"
          http_route:
            insecure: "{{ argocd_vars.kubernetes.server.gateway.service }}-http"
            secure: "{{ argocd_vars.kubernetes.server.gateway.service }}-https"
      ingress:
        class:
          name: cilium
        server:
          annotations:
            ingress.cilium.io/tls-passthrough: enabled
      helm:
        chart:
          reference: "{{ argocd_vars.kubernetes.helm.repository.org }}/{{ argocd_vars.kubernetes.helm.chart.name }}"
          version: "{{ argocd_vars.kubernetes.helm.chart.version[1:] }}"
        platform:
          key: https://github.com
          raw: https://raw.githubusercontent.com
        repository:
          name: "{{ argocd_vars.kubernetes.helm.repository.org }}/{{ argocd_vars.kubernetes.helm.repository.name }}"
          url: "{{ argocd_vars.kubernetes.helm.repository.url }}/{{ argocd_vars.kubernetes.helm.repository.name }}"
        timeout: 10m0s
      metrics:
        service:
          monitor:
            enabled: true
            scrape:
              # If `null`, default value is `victoriametrics_map.service.monitor.scrape.interval`
              interval: null
              # If `null`, default value is `victoriametrics_map.service.monitor.scrape.timeout`
              timeout: null
  run_once: true

- name: Set project fact
  ansible.builtin.set_fact:
    argocd_project:
      release:
        checksum: "{{ argocd_vars.release.version }}/{{ argocd_vars.release.checksum }}"
        file: "{{ argocd_vars.release.version }}/{{ argocd_vars.release.file_map[ansible_architecture] }}"
        url: "{{
          '/'.join([argocd_map.helm.platform.key,
          argocd_vars.release.repository.org,
          argocd_vars.release.repository.name, 'releases', 'download'])
          }}"
      tag: "{{ argocd_vars.kubernetes.helm.chart.name }}-{{ argocd_map.helm.chart.version }}"
      url: "{{ argocd_map.helm.platform.key }}/{{ argocd_map.helm.repository.name }}/releases/tag"
  run_once: true

- name: Set resources fact
  ansible.builtin.set_fact:
    argocd_resources:
      server:
        users:
          - name: "{{ argocd_map.credentials.server.user.name }}"
            password: "{{ argocd_map.credentials.server.user.password }}"
            permissions: "apiKey, login"
            role: admin
            enabled: true
