---
- name: Role Facts
  ansible.builtin.import_role:
    name: k3s
    tasks_from: facts

- name: Role Reset
  when: inventory_hostname in k3s_map.server.hosts
  block:
    - name: Reset Chart
      include_tasks: roles/_common/tasks/reset_chart.yaml
      vars:
        repository_name: "{{ argocd_vars.kubernetes.helm.repository.org }}"
        binary_files:
          - argocd
