---
- name: Role Facts
  ansible.builtin.include_role:
    name: "{{ role }}"
    tasks_from: facts
  loop:
    - cert-manager
    - external-dns
    - k3s
    - victoria-metrics
    - argo-cd
  loop_control:
    loop_var: role

- name: Role Validation
  when: ('validation' in ansible_run_tags)
  run_once: true
  block:
    - name: Validate project url
      ansible.builtin.uri:
        url: "{{ argocd_project.url }}/{{ argocd_project.tag }}"
        timeout: 5
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Validate release checksum url
      ansible.builtin.uri:
        url: "{{ argocd_project.release.url }}/{{ argocd_project.release.checksum }}"
        timeout: 5
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Validate release file url
      ansible.builtin.uri:
        url: "{{ argocd_project.release.url }}/{{ argocd_project.release.file }}"
        timeout: 5
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Chart Validation
      block:
        - name: Add repository
          kubernetes.core.helm_repository:
            name: "{{ argocd_vars.kubernetes.helm.repository.org }}"
            repo_url: "{{ argocd_map.helm.repository.url }}"

        - name: Get deployed chart release info
          kubernetes.core.helm_info:
            kubeconfig: "{{ k3s_project.cluster.kubeconfig }}"
            name: "{{ argocd_vars.kubernetes.helm.chart.name }}"
            namespace: "{{ argocd_vars.kubernetes.namespace }}"
          register: release
          changed_when: false

        - name: Set comparison fact
          ansible.builtin.set_fact:
            comparison:
              chart: "{{ argocd_map.helm.chart.version }}"
              release: "{{ (release.status.chart | default('0')).split('-')[-1] }}"

        - name: Validate configuration params values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'config_params.j2') | trim }}"

        - name: Validate configuration rbac values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'config_rbac.j2') | trim }}"

        - name: Validate credentials values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'credentials.j2') }}"

        - name: Validate gateway values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'gateway.j2') }}"

        - name: Validate insecure http route values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'http_route_insecure.j2') }}"

        - name: Validate secure http route values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'http_route_secure.j2') }}"

        - name: Set chart postinstall fact
          ansible.builtin.set_fact:
            argocd_postinstall: false

        - name: Validate chart values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'values.j2') }}"

        - name: Set chart values fact
          ansible.builtin.set_fact:
            chart_values: "{{ lookup('ansible.builtin.template', 'values.j2') | trim | from_yaml }}"
          when:
            - comparison.release is version('0', '>')
            - comparison.release != comparison.chart

        - name: Update chart postinstall fact
          ansible.builtin.set_fact:
            argocd_postinstall: true

        - name: Validate postinstall chart values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'values.j2') }}"

        - name: Chart Deployment Simulation
          when:
            - comparison.release is version('0', '>')
            - comparison.release != comparison.chart
          block:
            - name: Update chart values fact
              ansible.builtin.set_fact:
                chart_values: "{{ chart_values | combine(lookup('ansible.builtin.template', 'values.j2') | trim | from_yaml, recursive=true) }}"

            - name: Simulate chart deployment
              ansible.builtin.command:
                cmd: >-
                  helm diff upgrade
                    {{ argocd_vars.kubernetes.helm.chart.name }}
                    {{ argocd_map.helm.chart.reference }}
                    --kubeconfig {{ k3s_project.cluster.kubeconfig }}
                    --namespace {{ argocd_vars.kubernetes.namespace }}
                    --version {{ argocd_vars.kubernetes.helm.chart.version }}
                    --context 3 --values -
                stdin: "{{ chart_values | to_yaml }}"
              register: result
              delay: 1
              retries: 3
              until: result is not failed
              changed_when: false

            - name: Chart deployment simulation result
              ansible.builtin.debug:
                msg: "{{ result.stdout if result.stdout | length > 0 else 'No chart deployment errors found.' }}"

            - name: Compare chart values
              ansible.builtin.command:
                cmd: bash -c "{{
                  ' '.join(['diff', '-u', '<(curl', '-s ' +
                  '/'.join([argocd_map.helm.platform.raw,
                  argocd_vars.kubernetes.helm.repository.org,
                  argocd_vars.kubernetes.helm.repository.name, 'refs', 'tags',
                  '-'.join([argocd_vars.kubernetes.helm.chart.name, comparison.release]), 'charts',
                  argocd_vars.kubernetes.helm.chart.name, 'values.yaml']) + ')',
                  '<(curl', '-s ' +
                  '/'.join([argocd_map.helm.platform.raw,
                  argocd_vars.kubernetes.helm.repository.org,
                  argocd_vars.kubernetes.helm.repository.name, 'refs', 'tags',
                  '-'.join([argocd_vars.kubernetes.helm.chart.name, comparison.chart]), 'charts',
                  argocd_vars.kubernetes.helm.chart.name, 'values.yaml']) + ')'])
                  }}"
              register: result
              delay: 1
              retries: 3
              until: result is not failed
              changed_when: false
              failed_when: result.rc > 1

            - name: Chart values comparison result
              ansible.builtin.debug:
                msg: "{{ result.stdout if result.stdout | length > 0 else 'No chart comparison changes found.' }}"
