---
- name: Tags Validation
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Validate tags
      ansible.builtin.fail:
        msg: |
          Improper usage of '--tags' flag:
          {% set invalid_tags = ansible_run_tags | difference(global_map.tags.play) %}
          {% if invalid_tags | length > 0 %}
            - invalid tag{% if invalid_tags | length > 1 %}s{% endif %}: {{ invalid_tags | join(', ') }}
          {% endif %}
            - valid tags: {{ global_map.tags.play | join(', ') }}
      tags: always
      when:
        - ansible_run_tags not in [[], ['all']]
        - ansible_run_tags | difference(global_map.tags.play) | length > 0

- name: LoadBalancer Provisioning
  hosts: cluster
  become: true
  gather_facts: true
  tags:
    - kubernetes
  tasks:
    - name: Setup loadbalancer
      ansible.builtin.import_role:
        name: k3s
        tasks_from: loadbalancer

- name: Kubernetes Provisioning
  hosts: cluster
  become: true
  gather_facts: true
  roles:
    - helm
    - k3s
  serial:
    - 1
    - 2
    - 5
  tags: kubernetes

- name: Charts Provisioning
  hosts: server
  become: true
  gather_facts: true
  roles:
    - { role: cilium, tags: [charts, cilium] }
    - { role: coredns, tags: [charts, coredns] }
    - { role: cert-manager, tags: [charts, cert-manager] }
    - { role: external-dns, tags: [charts, external-dns] }
    - { role: longhorn, tags: [charts, longhorn] }
    - { role: metrics-server, tags: [charts, metrics-server] }
    - { role: kured, tags: [charts, kured] }
    - { role: victoria-logs, tags: [charts, victoria-logs] }
    - { role: victoria-metrics, tags: [charts, victoria-metrics] }
    - { role: argo-cd, tags: [charts, argo-cd] }
    - { role: k8s-dashboard, tags: [charts, k8s-dashboard] }
