---
- name: Tags Validation
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Validate tags
      ansible.builtin.fail:
        msg: |
          Improper usage of '--tags' flag:
          {% set invalid_tags = ansible_run_tags | difference(global_map.tags.role | union(['validation'])) %}
          {% if invalid_tags | length > 0 %}
            - invalid tag{% if invalid_tags | length > 1 %}s{% endif %}: {{ invalid_tags | join(', ') }}
          {% endif %}
          {% if 'validation' not in ansible_run_tags %}
            - required tag: validation
          {% endif %}
            - valid tags: {{ global_map.tags.role | join(', ') }}
      tags: always
      when:
        - ansible_run_tags not in [[], ['all']]
        - >-
          ('validation' not in ansible_run_tags) or
          (ansible_run_tags | difference(global_map.tags.role | union(['validation'])) | length > 0)

- name: Cluster Validation
  hosts: cluster
  become: true
  gather_facts: true
  tasks:
    - name: Validate global settings
      ansible.builtin.include_role:
        apply:
          tags: "{{ validation }}"
        name: "{{ validation }}"
        tasks_from: validation
      loop: "{{ global_map.tags.role }}"
      loop_control:
        loop_var: validation
      tags: always
      when: (ansible_run_tags == ['all']) or (validation in ansible_run_tags)
