---
# Improved dependency manager with resilience

- name: Set Debug Mode
  ansible.builtin.set_fact:
    debug_mode: "{{ lookup('env', 'DEBUG') | default(false, true) | bool }}"

- name: Process Component Dependencies
  include_tasks: roles/_common/tasks/dependency_framework.yaml
  vars:
    role_name: "{{ component_name }}"

- name: Deploy Component
  include_role:
    name: "{{ component_name }}"
  when: missing_required | length == 0
