---
- name: Role Facts
  ansible.builtin.include_role:
    name: "{{ role }}"
    tasks_from: facts
  loop:
    - external-dns
    - longhorn
    - k3s
  loop_control:
    loop_var: role

- name: Role Reset
  block:
    - name: Remove Repository
      include_tasks: roles/_common/tasks/reset_chart.yaml
      vars:
        repository_name: "{{ longhorn_vars.kubernetes.helm.repository.org }}"
        binary_files:
          - longhornctl
      when: inventory_hostname in k3s_map.server.hosts

    - name: Remove directory
      ansible.builtin.file:
        path: "{{ longhorn_map.directory.data }}"
        state: absent
