---
ansible_user: admin
# -- Encrypt value with ansible-vault
ansible_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  [encrypted-password-here]
ansible_become_password: "{{ ansible_password }}"
# Global configuration and credentials
global_map:
  credentials:
    argocd:
      server:
        admin:
          password: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            [encrypted-password-here]
        user:
          name: admin
          password: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            [encrypted-password-here]
    externaldns:
      cloudflare:
        api:
          token: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            [encrypted-token-here]
    kured:
      slack:
        notify:
          url: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            [encrypted-url-here]
    longhorn:
      backup:
        user:
          name: backup
          password: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            [encrypted-password-here]
      encryption:
        key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          [encrypted-key-here]
    victoriametrics:
      grafana:
        user:
          name: admin
          password: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            [encrypted-password-here]
  k3s:
    encryption:
      key: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        [encrypted-key-here]
  tags:
    play:
      - charts
      - cluster
      - kubernetes
    role:
      - argo-cd
      - cert-manager
      - cilium
      - coredns
      - external-dns
      - helm
      - k3s
      - kured
      - longhorn
      - metrics-server
      - victoria-logs
      - victoria-metrics
