---
# This file defines the dependencies between components

# Required dependencies that must be present
component_dependencies:
  # Core infrastructure
  k3s: [] # Base component, no dependencies
  helm: [k3s] # Needs working k3s

  # Networking and core components
  cilium: [k3s, helm] # Replaces kube-proxy and flannel
  coredns: [k3s, helm, cilium] # Needs CNI for DNS resolution

  # Security and service discovery
  cert-manager: [k3s, helm, cilium] # Needs networking
  external-dns: [k3s, helm, cilium, cert-manager] # Needs cert-manager for ACME

  # Storage
  longhorn: [k3s, helm, cilium] # Needs networking

  # Applications and utilities
  metrics-server: [k3s, helm, cilium]
  kured: [k3s, helm, cilium]

  # Monitoring and logging
  victoria-metrics: [k3s, helm, cilium, cert-manager]
  victoria-logs: [k3s, helm, cilium, cert-manager]

  # UI and deployment tools
  argo-cd: [k3s, helm, cilium, cert-manager]
  k8s-dashboard: [k3s, helm, cilium, cert-manager]

# Optional dependencies that enhance functionality but aren't required
component_optional_dependencies:
  # Core infrastructure has no optional dependencies
  k3s: []
  helm: []
  cilium: []
  coredns: []

  # Components that work better with storage but don't strictly require it
  cert-manager: []
  external-dns: []
  metrics-server: []
  kured: []

  # Monitoring components work better with persistent storage
  victoria-metrics: [longhorn]
  victoria-logs: [longhorn]

  # Application tools
  argo-cd: [external-dns]
  k8s-dashboard: [external-dns]

# Component verification settings
component_verification:
  default:
    retries: 30
    delay: 10
  longhorn: # Storage initialization can take longer
    retries: 45
    delay: 20
  victoria-metrics: # Complex statefulsets take time
    retries: 40
    delay: 15
