---
- name: Set map fact
  ansible.builtin.set_fact:
    victoriametrics_map:
      credentials:
        grafana:
          secret: "{{ victoriametrics_vars.kubernetes.helm.chart.victoriametrics.alias }}-grafana-credentials"
      helm:
        chart:
          - name: "{{ victoriametrics_vars.kubernetes.helm.chart.prometheus.name }}"
            version: "{{ victoriametrics_vars.kubernetes.helm.chart.prometheus.version[1:] }}"
          - name: "{{ victoriametrics_vars.kubernetes.helm.chart.victoriametrics.name }}"
            version: "{{ victoriametrics_vars.kubernetes.helm.chart.victoriametrics.version[1:] }}"
        platform:
          key: https://github.com
          raw: https://raw.githubusercontent.com
        repository:
          - name: "{{ victoriametrics_vars.kubernetes.helm.repository.grafana.name }}"
            org: "{{ victoriametrics_vars.kubernetes.helm.repository.grafana.org }}"
            url: "{{ victoriametrics_vars.kubernetes.helm.repository.grafana.url }}"
          - name: "{{ victoriametrics_vars.kubernetes.helm.repository.prometheus.name }}"
            org: "{{ victoriametrics_vars.kubernetes.helm.repository.prometheus.org }}"
            url: "{{ victoriametrics_vars.kubernetes.helm.repository.prometheus.url }}"
          - name: "{{ victoriametrics_vars.kubernetes.helm.repository.victoriametrics.name }}"
            org: "{{ victoriametrics_vars.kubernetes.helm.repository.victoriametrics.org }}"
            url: "{{ victoriametrics_vars.kubernetes.helm.repository.victoriametrics.url }}"
        timeout: 10m0s
      ingress:
        alertmanager:
          annotations:
            cert-manager.io/cluster-issuer: "{{ externaldns_project.cloudflare.cluster.issuer }}"
          hostname: "{{ victoriametrics_vars.kubernetes.alertmanager.ingress.subdomain }}.{{ externaldns_vars.cloudflare.host.domain }}"
          name: "{{
            '-'.join(['alertmanager',
            victoriametrics_vars.kubernetes.helm.chart.victoriametrics.alias,
            victoriametrics_vars.kubernetes.helm.chart.victoriametrics.name])
            }}"
        class:
          name: cilium
        grafana:
          annotations:
            cert-manager.io/cluster-issuer: "{{ externaldns_project.cloudflare.cluster.issuer }}"
          hostname: "{{ victoriametrics_vars.kubernetes.grafana.ingress.subdomain }}.{{ externaldns_vars.cloudflare.host.domain }}"
          name: "{{ victoriametrics_vars.kubernetes.helm.chart.victoriametrics.alias }}-grafana"
        vmagent:
          annotations:
            cert-manager.io/cluster-issuer: "{{ externaldns_project.cloudflare.cluster.issuer }}"
          hostname: "{{ victoriametrics_vars.kubernetes.vmagent.ingress.subdomain }}.{{ externaldns_vars.cloudflare.host.domain }}"
          name: "{{
            '-'.join(['vmagent',
            victoriametrics_vars.kubernetes.helm.chart.victoriametrics.alias,
            victoriametrics_vars.kubernetes.helm.chart.victoriametrics.name])
            }}"
        vmalert:
          annotations:
            cert-manager.io/cluster-issuer: "{{ externaldns_project.cloudflare.cluster.issuer }}"
          hostname: "{{ victoriametrics_vars.kubernetes.vmalert.ingress.subdomain }}.{{ externaldns_vars.cloudflare.host.domain }}"
          name: "{{
            '-'.join(['vmalert',
            victoriametrics_vars.kubernetes.helm.chart.victoriametrics.alias,
            victoriametrics_vars.kubernetes.helm.chart.victoriametrics.name])
            }}"
        vmcluster:
          vminsert:
            annotations:
              cert-manager.io/cluster-issuer: "{{ externaldns_project.cloudflare.cluster.issuer }}"
            hostname: "{{ victoriametrics_vars.kubernetes.vmcluster.vminsert.ingress.subdomain }}.{{ externaldns_vars.cloudflare.host.domain }}"
            name: "{{
              '-'.join(['vminsert',
              victoriametrics_vars.kubernetes.helm.chart.victoriametrics.alias,
              victoriametrics_vars.kubernetes.helm.chart.victoriametrics.name])
              }}"
          vmselect:
            annotations:
              cert-manager.io/cluster-issuer: "{{ externaldns_project.cloudflare.cluster.issuer }}"
            hostname: "{{ victoriametrics_vars.kubernetes.vmcluster.vmselect.ingress.subdomain }}.{{ externaldns_vars.cloudflare.host.domain }}"
            name: "{{
              '-'.join(['vmselect',
              victoriametrics_vars.kubernetes.helm.chart.victoriametrics.alias,
              victoriametrics_vars.kubernetes.helm.chart.victoriametrics.name])
              }}"
          vmstorage:
            annotations:
              cert-manager.io/cluster-issuer: "{{ externaldns_project.cloudflare.cluster.issuer }}"
            hostname: "{{ victoriametrics_vars.kubernetes.vmcluster.vmstorage.ingress.subdomain }}.{{ externaldns_vars.cloudflare.host.domain }}"
            name: "{{
              '-'.join(['vmstorage',
              victoriametrics_vars.kubernetes.helm.chart.victoriametrics.alias,
              victoriametrics_vars.kubernetes.helm.chart.victoriametrics.name])
              }}"
        vmsingle:
          annotations:
            cert-manager.io/cluster-issuer: "{{ externaldns_project.cloudflare.cluster.issuer }}"
          hostname: "{{ victoriametrics_vars.kubernetes.vmsingle.ingress.subdomain }}.{{ externaldns_vars.cloudflare.host.domain }}"
          name: "{{
            '-'.join(['vmsingle',
            victoriametrics_vars.kubernetes.helm.chart.victoriametrics.alias,
            victoriametrics_vars.kubernetes.helm.chart.victoriametrics.name])
            }}"
      service:
        monitor:
          scrape:
            interval: 30s
            timeout: 25s
      spec:
        alertmanager:
          extra_args: {}
          extra_envs: []
        vmagent:
          extra_args: {}
          extra_envs:
            # Reduce CPU usage, in favor of memory usage
            - name: GOGC
              # Default value is `30`
              value: "60"
        vmalert:
          extra_args: {}
          extra_envs: []
        vmcluster:
          vminsert:
            extra_args: {}
            extra_envs: []
          vmselect:
            extra_args: {}
            extra_envs: []
          vmstorage:
            extra_args: {}
            extra_envs: []
        vmsingle:
          extra_args: {}
          extra_envs:
            # Reduce CPU usage, in favor of memory usage
            - name: GOGC
              # Default value is `30`
              value: "60"
  run_once: true

- name: Set project fact
  ansible.builtin.set_fact:
    victoriametrics_project:
      helm:
        chart:
          prometheus:
            reference: "{{ victoriametrics_map.helm.repository[1].org }}/{{ victoriametrics_map.helm.chart[0].name }}"
            tag: "{{ victoriametrics_map.helm.chart[0].name }}-{{ victoriametrics_map.helm.chart[0].version }}"
            url: "{{
              '/'.join([victoriametrics_map.helm.platform.key,
              victoriametrics_map.helm.repository[1].org,
              victoriametrics_map.helm.repository[1].name, 'releases', 'tag'])
              }}"
          victoriametrics:
            reference: "{{ victoriametrics_map.helm.repository[2].org }}/{{ victoriametrics_map.helm.chart[1].name }}"
            tag: "{{ victoriametrics_map.helm.chart[1].name }}-{{ victoriametrics_map.helm.chart[1].version }}"
            url: "{{
              '/'.join([victoriametrics_map.helm.platform.key,
              victoriametrics_map.helm.repository[2].org,
              victoriametrics_map.helm.repository[2].name, 'releases', 'tag'])
              }}"
  run_once: true

- name: Set variables fact
  ansible.builtin.set_fact:
    victoriametrics_vars: "{{ victoriametrics_vars }}"
  run_once: true
