---
- name: Role Validation
  ansible.builtin.import_tasks:
    file: validation.yaml
  any_errors_fatal: true

- name: Role Provisioning
  when: inventory_hostname in k3s_map.server.hosts
  block:
    - name: Validate service state
      ansible.builtin.wait_for:
        port: "{{ k3s_vars.server.api.port }}"
        timeout: 30
      any_errors_fatal: true

    - name: Add repository
      kubernetes.core.helm_repository:
        name: "{{ item.org }}"
        repo_url: "{{ item.url }}/{{ item.name }}"
      loop: "{{ victoriametrics_map.helm.repository }}"

    - name: Chart Setup
      run_once: true
      block:
        - name: Create grafana user credentials secret
          kubernetes.core.k8s:
            definition: "{{ lookup('ansible.builtin.template', 'credentials.j2') | from_yaml }}"
            kubeconfig: "{{ k3s_project.cluster.kubeconfig }}"
            wait: true
          no_log: true

        - name: Install dependency chart
          kubernetes.core.helm:
            chart_ref: "{{ victoriametrics_project.helm.chart.prometheus.reference }}"
            chart_version: "{{ victoriametrics_vars.kubernetes.helm.chart.prometheus.version }}"
            kubeconfig: "{{ k3s_project.cluster.kubeconfig }}"
            name: "{{ victoriametrics_vars.kubernetes.helm.chart.prometheus.name }}"
            namespace: "{{ victoriametrics_vars.kubernetes.namespace }}"
            timeout: "{{ victoriametrics_map.helm.timeout }}"
            create_namespace: true
            update_repo_cache: true
            wait: true
          register: result
          delay: 1
          retries: 3
          until: result is not failed

        - name: Install chart
          kubernetes.core.helm:
            chart_ref: "{{ victoriametrics_project.helm.chart.victoriametrics.reference }}"
            chart_version: "{{ victoriametrics_vars.kubernetes.helm.chart.victoriametrics.version }}"
            kubeconfig: "{{ k3s_project.cluster.kubeconfig }}"
            name: "{{ victoriametrics_vars.kubernetes.helm.chart.victoriametrics.alias }}"
            namespace: "{{ victoriametrics_vars.kubernetes.namespace }}"
            timeout: "{{ victoriametrics_map.helm.timeout }}"
            values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"
            update_repo_cache: true
            wait: true
          register: result
          delay: 1
          retries: 3
          until: result is not failed
