---
longhorn_vars:
  kubernetes:
    backup:
      enabled: true
      poll_interval: 300
      target: cifs://nas.noty.cc/backup
    default_settings:
      collect_usage_metrics: false
      concurrent_automatic_engine_upgrade_limit: 1
      data_locality: best-effort
      log_level: Warn
      node_drain_policy: block-for-eviction
      pod_deletion_policy: delete-both-statefulset-and-deployment-pod
      volume:
        replica_auto_balance: least-effort
        replicas: 2
      # Encryption settings
      csi_encryption: true
      csi_encryption_kms_type: "kubernetes-secret"
      csi_encryption_kms_secret_name: "longhorn-crypto-key"
      csi_encryption_kms_secret_namespace: "kube-system"
    frontend:
      gateway:
        service: longhorn-frontend
        subdomain: longhorn
      ingress:
        enabled: false
    helm:
      chart:
        name: longhorn
        version: v1.8.1
      repository:
        name: longhorn
        org: longhorn
        url: https://charts.longhorn.io
    namespace: kube-system
    # Storage classes for encrypted and unencrypted volumes
    storage_classes:
      - name: longhorn
        default: true
        encrypted: false
      - name: longhorn-encrypted
        default: false
        encrypted: true
        parameters:
          encrypted: "true"
          # Use 'luks' (or 'luks2') for Linux Unified Key Setup
          encryption-type: "luks"
  release:
    file: longhornctl-linux-{{ ansible_architecture }}
    repository:
      name: cli
      org: longhorn
    version: v1.8.1
  encryption:
    enabled: true
    rotation_interval: 90d # Rotate encryption keys every 90 days
