---
longhorn_vars:
  kubernetes:
    backup:
      enabled: true
      poll_interval: 300

      target: cifs://nas.noty.cc/backup
    default_settings:
      collect_usage_metrics: false

      concurrent_automatic_engine_upgrade_limit: 1

      data_locality: best-effort
      log_level: Warn

      node_drain_policy: block-for-eviction

      pod_deletion_policy: delete-both-statefulset-and-deployment-pod
      volume:
        replica_auto_balance: least-effort

        replicas: 2
    frontend:
      gateway:
        service: longhorn-frontend

        subdomain: longhorn
      ingress:
        # -- If `false`, HTTPRoute is used, otherwise Ingress
        enabled: false
    helm:
      chart:
        name: longhorn
        version: v1.8.1
      repository:
        name: longhorn
        org: longhorn
        url: https://charts.longhorn.io
    namespace: kube-system
  release:
    file_map:
      x86_64: longhornctl-linux-amd64
      aarch64: longhornctl-linux-arm64
    repository:
      name: cli
      org: longhorn
    version: v1.8.1
