---
- name: Reboot
  ansible.builtin.reboot:

- name: Reload sysctl parameters
  ansible.builtin.command:
    cmd: sysctl --system
  changed_when: false

- name: Restart loadbalancer services
  ansible.builtin.systemd_service:
    name: "{{ services_item }}.service"
    state: restarted
    daemon_reload: true
    enabled: true
  loop:
    - haproxy
    - keepalived
  loop_control:
    loop_var: services_item

- name: Restart service
  ansible.builtin.systemd_service:
    name: "{{ k3s_map.service.name }}.service"
    state: restarted
    daemon_reload: true
    enabled: true

- name: Start service
  ansible.builtin.systemd_service:
    name: "{{ k3s_map.service.name }}.service"
    state: started
    daemon_reload: true
    enabled: true

- name: Stop service
  ansible.builtin.systemd_service:
    name: "{{ k3s_map.service.name }}.service"
    state: stopped
    enabled: false
  register: service
  failed_when:
    - service.failed == true
    - service.msg.find('Could not find the requested service') == -1
