---
- name: Role Facts
  ansible.builtin.include_role:
    name: "{{ role }}"
    tasks_from: facts
  loop:
    - cluster
    - k3s
  loop_control:
    loop_var: role

- name: Loadbalancer Setup
  notify: Restart loadbalancer services
  when:
    - k3s_map.server.ha is truthy
    - inventory_hostname in k3s_map.loadbalancer.hosts
  block:
    - name: Set sysctl token value
      ansible.posix.sysctl:
        name: net.ipv4.ip_nonlocal_bind
        value: "1"
        sysctl_file: /etc/sysctl.d/90-ip-nonlocal-bind.conf
        sysctl_set: true

    - name: Install loadbalancer packages
      ansible.builtin.apt:
        name: "{{ item }}"
        autoremove: true
        update_cache: true
      loop:
        - haproxy
        - keepalived
        - curl
        - mailutils # For email notifications

    - name: Update haproxy configuration file
      ansible.builtin.template:
        src: haproxy.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: "0644"
      notify: Restart loadbalancer services

    - name: Update keepalived configuration file
      ansible.builtin.template:
        src: keepalived.j2
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: "0644"
      notify: Restart loadbalancer services

    - name: Install K3s API health check script
      ansible.builtin.template:
        src: check_k3s_api.sh.j2
        dest: /usr/local/bin/check_k3s_api.sh
        owner: root
        group: root
        mode: "0755"
      notify: Restart loadbalancer services

    - name: Install keepalived notification script
      ansible.builtin.template:
        src: keepalived-notify.sh.j2
        dest: /usr/local/bin/keepalived-notify.sh
        owner: root
        group: root
        mode: "0755"
      notify: Restart loadbalancer services

    - name: Create log file for keepalived state changes
      ansible.builtin.file:
        path: /var/log/keepalived-state.log
        state: touch
        owner: root
        group: adm
        mode: "0640"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
