---
- name: Role Validation
  ansible.builtin.import_tasks:
    file: validation.yaml
  any_errors_fatal: true

- name: Role Provisioning
  notify: Start service
  block:
    - name: Install k3s binary
      ansible.builtin.get_url:
        url: "{{ k3s_project.release.k3s.file }}"
        checksum: sha256:{{ k3s_project.release.k3s.checksum }}
        dest: "{{ k3s_project.node.binary }}"
        owner: root
        group: root
        mode: "755"
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Create configuration directory
      ansible.builtin.file:
        path: "{{ k3s_map.node.directory.config }}"
        state: directory
        owner: root
        group: root
        mode: "755"

    - name: Set role postinstall fact
      ansible.builtin.set_fact:
        k3s_postinstall: false

    - name: Create configuration file
      ansible.builtin.template:
        src: config.j2
        dest: "{{ k3s_project.cluster.config }}"
        owner: root
        group: root
        mode: "600"

    - name: Create service file
      ansible.builtin.template:
        src: service.j2
        dest: /etc/systemd/system/{{ k3s_map.service.name }}.service
        owner: root
        group: root
        mode: "644"

    - name: Create service environment file
      ansible.builtin.file:
        path: /etc/systemd/system/{{ k3s_map.service.name }}.service.env
        access_time: preserve
        modification_time: preserve
        state: touch
        owner: root
        group: root
        mode: "600"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Role Configuration
  ansible.builtin.import_tasks:
    file: configuration.yaml

- name: Server Configuration
  notify: Restart service
  when: inventory_hostname in k3s_map.server.hosts
  block:
    - name: Set role postinstall fact
      ansible.builtin.set_fact:
        k3s_postinstall: true

    - name: Update server configuration file
      ansible.builtin.template:
        src: config.j2
        dest: "{{ k3s_project.cluster.config }}"
        owner: root
        group: root
        mode: "600"
