---
- name: Upgrade Chart
  kubernetes.core.helm:
    chart_ref: "{{ chart_ref }}"
    chart_version: "{{ chart_version }}"
    kubeconfig: "{{ k3s_project.cluster.kubeconfig }}"
    name: "{{ chart_name }}"
    namespace: "{{ chart_namespace }}"
    timeout: "{{ chart_timeout | default('5m0s') }}"
    values: "{{ chart_values }}"
    wait: true
  register: result
  delay: 1
  retries: 3
  until: result is not failed