# roles/_common/tasks/validation.yaml
- name: Validate project URL
  ansible.builtin.uri:
    url: "{{ project_url }}"
    timeout: 5
  register: result
  delay: 1
  retries: 3
  until: result is not failed

- name: Validate chart version
  kubernetes.core.helm_info:
    kubeconfig: "{{ k3s_project.cluster.kubeconfig }}"
    name: "{{ release_name }}"
    namespace: "{{ namespace }}"
  register: release
  changed_when: false

- name: Set comparison fact
  ansible.builtin.set_fact:
    comparison:
      chart: "{{ expected_version }}"
      release: "{{ (release.status.chart | default('0')).split('-')[-1] }}"