---
- name: Role Validation
  ansible.builtin.import_tasks:
    file: validation.yaml
  any_errors_fatal: true

- name: Verify Dependencies
  ansible.builtin.import_tasks:
    file: verify_dependencies.yaml
  any_errors_fatal: true

- name: Role Provisioning
  when: inventory_hostname in k3s_map.server.hosts
  block:
    - name: Validate service state
      ansible.builtin.wait_for:
        port: "{{ k3s_vars.server.api.port }}"
        timeout: 30
      any_errors_fatal: true

    - name: Add repository
      kubernetes.core.helm_repository:
        name: "{{ coredns_vars.kubernetes.helm.repository.org }}"
        repo_url: "{{ coredns_map.helm.repository.url }}"

    - name: Chart Setup
      run_once: true
      block:
        - name: Set chart postinstall fact
          ansible.builtin.set_fact:
            coredns_postinstall: false

        - name: Install chart
          include_tasks: roles/_common/tasks/upgrade_chart.yaml
          vars:
            chart_ref: "{{ coredns_map.helm.chart.reference }}"
            chart_version: "{{ coredns_vars.kubernetes.helm.chart.version }}"
            chart_name: "{{ coredns_vars.kubernetes.helm.chart.name }}"
            chart_namespace: "{{ coredns_vars.kubernetes.namespace }}"
            chart_timeout: "{{ coredns_map.helm.timeout }}"
            chart_values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"

- name: Verify CoreDNS Deployment
  run_once: true
  include_role:
    name: verification
  vars:
    component_name: "CoreDNS"
    component_namespace: "{{ coredns_vars.kubernetes.namespace }}"
    component_type: "deployment"
    component_value: "{{ coredns_vars.kubernetes.helm.chart.name }}"
  when:
    - inventory_hostname in k3s_map.server.hosts
    - lookup('env', 'SKIP_VERIFICATION') | default('false') | lower != 'true'