---
k3s_vars:
  cluster:
    controlplane:
      tainted: true
    domain: cluster.local
    kubeconfig:
      local: true
      path: "{{ lookup('ansible.builtin.env', 'HOME') + '/.kube' }}"
    service:
      host: 127.0.0.1
      port: 6444
    tls_san:
      - 192.168.4.10
  network:
    interface: eth0
  release:
    k3s:
      name: k3s
      repository:
        name: k3s
        org: k3s-io
      version: v1.32.3+k3s1
    kubepug:
      name: kubepug
      repository:
        name: kubepug
        org: kubepug
      version: v1.7.1
  server:
    api:
      host: 192.168.4.10
      port: 6443
  service:
    debug: false
  encryption:
    enabled: true
    key_rotation_interval: 30d # Rotate keys every 30 days
