---
k3s_vars:
  cluster:
    controlplane:
      tainted: true
    domain: cluster.local
    kubeconfig:
      local: true
      # -- Local `/.kube` directory path
      path: "{{ lookup('ansible.builtin.env', 'HOME') + '/.kube' }}"
    service:
      host: 127.0.0.1
      port: 6444
    # -- Related to `server.api.host` key
    tls_san:
      - 192.168.4.10
  network:
    interface: eth0
  release:
    k3s:
      checksum_map:
        x86_64: sha256sum-amd64.txt
        aarch64: sha256sum-arm64.txt
      file_map:
        x86_64: k3s
        aarch64: k3s-arm64
      name: k3s
      repository:
        name: k3s
        org: k3s-io
      version: v1.32.3+k3s1
    kubepug:
      checksum: checksums.txt
      file_map:
        x86_64: kubepug_linux_amd64.tar.gz
        aarch64: kubepug_linux_arm64.tar.gz
      name: kubepug
      repository:
        name: kubepug
        org: kubepug
      version: v1.7.1
  server:
    api:
      # -- Related to `cluster.tls_san` key,
      # used as frontend bind IP for Haproxy loadbalancer and populated into `/.kube/config` file
      host: 192.168.4.10
      port: 6443
  service:
    debug: false
  encryption:
    enabled: true
    key: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits', 'punctuation'], length=32) }}"
    config_path: "/var/lib/rancher/k3s/server/encryption-config.yaml"
    rotate_keys: false # Set to true when key rotation is needed
    old_key: "" # Previous key used during rotation
