---
- name: Verify {{ component_name }} StatefulSet Is Ready
  kubernetes.core.k8s_info:
    kubeconfig: "{{ k3s_project.cluster.kubeconfig }}"
    kind: StatefulSet
    namespace: "{{ component_namespace }}"
    name: "{{ component_value }}"
  register: component_statefulset
  until: >
    component_statefulset.resources is defined and
    component_statefulset.resources | length > 0 and
    component_statefulset.resources[0].status.readyReplicas is defined and
    component_statefulset.resources[0].status.readyReplicas == component_statefulset.resources[0].status.replicas
  retries: "{{ verification_retries | default(30) }}"
  delay: "{{ verification_delay | default(10) }}"

- name: Log Status on Success
  ansible.builtin.debug:
    msg: "✅ {{ component_name }} statefulset is ready"
  when:
    - component_statefulset.resources is defined
    - component_statefulset.resources | length > 0
    - component_statefulset.resources[0].status.readyReplicas is defined
    - component_statefulset.resources[0].status.replicas is defined
    - component_statefulset.resources[0].status.readyReplicas == component_statefulset.resources[0].status.replicas